uptime-kuma:
    volume:
        enabled: true
        storageClassName: local-path
        accessMode: ReadWriteOnce
        size: 5Gi

    ingress:
        enabled: true
        className: traefik

        hosts:
            - host: kuma.lab.local
              paths:
              - path: /
                pathType: Prefix