persistence:
  enabled: true
  storageClass: local-path
  accessMode: ReadWriteOnce
  size: 5Gi

ingress:
    enabled: true
    className: traefik

    hosts:
        - host: kuma.lab.local
          paths:
              - path: /
                pathType: Prefix