kube-prometheus-stack:

  crds:
    enabled: true

  upgradeJob:
    enabled: false

  prometheusOperator:
    enabled: true

  grafana:
    enabled: false

  alertmanager:
    enabled: false

  prometheus:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - prometheus.lab.local
      pathType: Prefix

    prometheusSpec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        runAsNonRoot: false
        seccompProfile:
            type: RuntimeDefault
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi