argo-cd:
  global:
    domain: argocd.lab.local
  configs:
    params:
      server.insecure: true

  server:
    extraEnv:
      - name: TZ
        value: Africa/Johannesburg

    ingress:
      enabled: true
      ingressClassName: traefik

      hostname: argocd.lab.local

      annotations:
        cert-manager.io/cluster-issuer: selfsigned-issuer
        traefik.ingress.kubernetes.io/service.serversscheme: http

      tls: true

  controller:
    extraEnv:
      - name: TZ
        value: Africa/Johannesburg

  repoServer:
    extraEnv:
      - name: TZ
        value: Africa/Johannesburg

monitors:
  argocd:
    name: ArgoCD
    url: http://argocd-server.argocd:80
    type: http
    interval: 60
    retries: 3