argo-cd:

    configs:
        params:
            server.insecure: true

    server:
        ingress:
            enabled: true
            ingressClassName: traefik

            hosts:
                - argocd.lab.local

            tls:
                - secretName: argocd-tls
                  hosts:
                      - argocd.lab.local

            annotations:
                cert-manager.io/cluster-issuer: selfsigned-issuer