server:
    insecure: true
    extraArgs:
        - --insecure
    ingress:
        enabled: true
        hosts:
            - argocd.lab.local
        tlsSecretName: argocd-tls
        annotations:
            cert-manager.io/cluster-issuer: selfsigned-issuer
            kubernetes.io/ingress.class: traefik
config:
    rbac:
        policy.csv: |
            g, admin, role:admin
#    params:
#        server.insecure: true